package com.msjl.langgraph4j.voiceguide.node;

import com.msjl.langgraph4j.voiceguide.agent.ExperienceVoiceGuideAgent;
import com.msjl.langgraph4j.voiceguide.agent.ExperienceVoiceGuideAgentRegistry;
import com.msjl.langgraph4j.voiceguide.agent.VoiceGuideContext;
import com.msjl.langgraph4j.voiceguide.domain.enums.VoiceGuideExperienceType;
import com.msjl.langgraph4j.voiceguide.domain.model.VoiceGuideDraft;
import com.msjl.langgraph4j.voiceguide.state.VoiceGuideState;
import org.bsc.langgraph4j.action.NodeAction;
import org.springframework.stereotype.Component;

import java.util.LinkedHashMap;
import java.util.Map;

@Component
public class ExperienceGuideNode implements NodeAction<VoiceGuideState> {

    private final ExperienceVoiceGuideAgentRegistry agentRegistry;

    public ExperienceGuideNode(ExperienceVoiceGuideAgentRegistry agentRegistry) {
        this.agentRegistry = agentRegistry;
    }

    @Override
    public Map<String, Object> apply(VoiceGuideState state) {
        VoiceGuideExperienceType type = state.experienceType()
                .orElseThrow(() -> new IllegalArgumentException("Experience type is required"));
        ExperienceVoiceGuideAgent agent = agentRegistry.get(type);
        VoiceGuideContext context = new VoiceGuideContext(
                state.sessionId().orElse(null),
                state.resumeId().orElse(null),
                state.targetJobTitle().orElse(null),
                type,
                state.currentContent().orElse(null),
                state.userLatestReply().orElse(null),
                state.globalInstruction().orElse(null),
                state.conversationHistory()
        );
        VoiceGuideDraft draft = agent.guide(context);

        Map<String, Object> updates = new LinkedHashMap<>();
        updates.put(VoiceGuideState.GUIDE_DRAFT, draft);
        updates.put(VoiceGuideState.EXECUTION_LOGS, "GUIDE: generated by " + draft.getAgentName());
        return updates;
    }
}
